version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: composer
    directory: /api
    schedule:
      interval: daily
    labels:
      - dependencies
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /pwa
    schedule:
      interval: daily
    labels:
      - dependencies
    open-pull-requests-limit: 5
