#!/usr/bin/env bash
#
# Generate a per-worktree .env so `docker compose` commands in this directory
# run in an isolated stack (unique project name, non-conflicting ports).
#
# Usage:
#   scripts/worktree-env.sh           # write ./.env for this worktree
#   scripts/worktree-env.sh --print   # print values without writing
#   scripts/worktree-env.sh --force   # overwrite an existing .env
#
# After running, use plain `docker compose up -d` / `docker compose down` as
# usual. Each worktree gets its own containers, volumes, and port mappings,
# so multiple stacks can run concurrently.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env"

print_only=0
force=0
for arg in "$@"; do
  case "$arg" in
    --print) print_only=1 ;;
    --force) force=1 ;;
    -h|--help)
      sed -n '2,15p' "$0"
      exit 0
      ;;
    *) echo "unknown arg: $arg" >&2; exit 2 ;;
  esac
done

# Detect whether this checkout is the main worktree or a linked worktree.
# The main checkout keeps default ports; linked worktrees get a hashed offset.
is_main_worktree=1
if git -C "$ROOT" rev-parse --git-dir >/dev/null 2>&1; then
  git_dir="$(git -C "$ROOT" rev-parse --git-dir)"
  case "$git_dir" in
    *"/worktrees/"*) is_main_worktree=0 ;;
  esac
fi

# Stable project slug from the worktree directory name.
slug="$(basename "$ROOT" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/^-*//;s/-*$//')"
project="aura-${slug:-main}"

if [ "$is_main_worktree" = "1" ]; then
  https_port=443
  http_port=80
  http3_port=443
  postgres_port=5432
  mailpit_smtp_port=1025
  mailpit_web_port=8025
else
  # Derive a port block from a hash of the absolute worktree path so the
  # same worktree always gets the same ports, and different worktrees
  # (almost) never collide. Range: 0..899 -> 900 distinct blocks.
  hash_hex="$(printf '%s' "$ROOT" | sha1sum | cut -c1-8)"
  hash_dec="$((16#$hash_hex))"
  block="$((hash_dec % 900))"

  https_port="$((20000 + block))"
  http_port="$((21000 + block))"
  http3_port="$https_port"
  postgres_port="$((25000 + block))"
  mailpit_smtp_port="$((26000 + block))"
  mailpit_web_port="$((27000 + block))"
fi

read -r -d '' body <<EOF || true
# Generated by scripts/worktree-env.sh — do not commit.
# Re-run the script to regenerate after moving the worktree.
COMPOSE_PROJECT_NAME=$project

SERVER_NAME=localhost
HTTP_PORT=$http_port
HTTPS_PORT=$https_port
HTTP3_PORT=$http3_port
POSTGRES_PORT=$postgres_port
MAILPIT_SMTP_PORT=$mailpit_smtp_port
MAILPIT_WEB_PORT=$mailpit_web_port

APP_FRONTEND_URL=https://localhost:$https_port
EOF

if [ "$print_only" = "1" ]; then
  printf '%s\n' "$body"
  exit 0
fi

if [ -e "$ENV_FILE" ] && [ "$force" = "0" ]; then
  echo "$ENV_FILE already exists. Pass --force to overwrite." >&2
  exit 1
fi

printf '%s\n' "$body" > "$ENV_FILE"
echo "Wrote $ENV_FILE"
echo "  project:     $project"
echo "  https:       https://localhost:$https_port"
echo "  mailpit UI:  http://localhost:$mailpit_web_port"
echo "  postgres:    localhost:$postgres_port"
